# -*- coding: utf-8 -*-
"""fake-news_model_with_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hf94ri1tuW5eigI2WDqyQvdX7Pdwt3Fm
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

fake_data = "/content/drive/MyDrive/Fake News detection/Fake.csv"
true_data = "/content/drive/MyDrive/Fake News detection/True.csv"

fake_df = pd.read_csv(fake_data)
true_df = pd.read_csv(true_data)

fake_df['label'] = 0
true_df['label'] = 1

df = pd.concat([fake_df , true_df], axis = 0 , ignore_index= False)
print(df.shape)

df = df.sample(frac=1,random_state = 42).reset_index(drop=True)
print(df['label'].sample(10))
print((df['label'].value_counts(normalize=True)*100).round(2))

columns_to_keep = ['title','text', 'label']

df = df[columns_to_keep]

df.head(5)

#cleaning the text (This boiler plate is used with the Helpof the AI )
import re
import string

def hard_clean_fake_news(text):
    # 1. Standardize and Lowercase
    text = str(text).lower()

    # 2. SURGICAL STRIKE: Remove Reuters/Location Signatures (The 99% Fix)
    # Pattern A: "City, State (Reuters) - "
    text = re.sub(r'^.*?\(reuters\)\s*[-:]', '', text)
    # Pattern B: "Washington Reuters -" or "Reuters -"
    text = re.sub(r'^\w*\s*reuters\s*[-:]', '', text)
    # Pattern C: Generic "Location - " (Matches any city name followed by a dash at start)
    text = re.sub(r'^\w+\s*[-:]', '', text)

    # 3. Remove Publisher Branding (e.g., 21st Century Wire)
    text = re.sub(r'21st century wire', '', text)

    # 4. Remove Twitter Handles (@username)
    text = re.sub(r'@\S+', '', text)

    # 5. Remove URLs and Twitter links
    text = re.sub(r'https?://\S+|www\.\S+|pic\.twitter\.com/\S+', '', text)

    # 6. Remove Dates (Month Day, Year)
    date_pattern = r'\b(january|february|march|april|may|june|july|august|september|october|november|december)\s+\d{1,2},?\s+\d{4}'
    text = re.sub(date_pattern, '', text)

    # 7. Remove Photo Credits and Getty Images Artifacts
    text = re.sub(r'photo by.*?(getty images|images)', '', text)
    text = re.sub(r'getty images', '', text)
    text = re.sub(r'image via', '', text)

    # 8. Remove "Read More" and Social Media Call-to-Actions (CTAs)
    # This cleans up the bottom of blog-scraped news
    text = re.sub(r'read more.*$', '', text)
    text = re.sub(r'watch the interview below.*', '', text)

    # 9. Final Cleanup: Punctuation, Newlines, and Multi-Spaces
    text = text.replace('\n', ' ')
    text = re.sub(f'[{re.escape(string.punctuation)}]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# --- Test Comparison ---
dirty_sample = "WASHINGTON (Reuters) - Donald J. Trump (@realDonaldTrump) December 31, 2017... Photo by Getty Images. Read more at 21st Century Wire."
clean_sample = hard_clean_fake_news(dirty_sample)

print(f"ORIGINAL: {dirty_sample}")
print(f"CLEANED : {clean_sample}")

#clean text
df['text'] = df['text'].apply(hard_clean_fake_news)

print(df['text'][0:10])

df.head(6)

df.to_csv('clean_data.csv')

